---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 89a3213e-f147-421f-8e3e-1c3252cd0a19
  labels:
    azure.workload.identity/use: "true"
  name: mysa
---
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  serviceAccountName: mysa
  containers:
    - name: mypod
      image: nginx:latest
      volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "mysecretproviderclass"
