kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  serviceAccountName: mysecretproviderclass
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
      #command:
        #- "/bin/sleep"
        #- "10000"
      env:
        - name: SUBSCRIPTION
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: subscription_id
        - name: TENANT
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: tenant_id
      volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "mysecretproviderclass"
