apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysecretproviderclass # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: 89a3213e-f147-421f-8e3e-1c3252cd0a19 # Setting this to use workload identity
    keyvaultName: mynewkeyvault02       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: subscription
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: tenant
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: client
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: a9a8e375-fac1-4ec2-820a-cfb6eb5cf01b      # The tenant ID of the key vault
  secretObjects:
  - secretName: mysecret
    type: Opaque
    data:
    - objectName: subscription
      key: subscription_id
    - objectName: tenant
      key: tenant_id
    - objectName: client
      key: client_id
    - objectName: secret
      key: client_secret
