apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  subscription_id: ZDEzOGMzNDQtYzY1Yi00ZTAxLWI4YWQtOWFkZmIxZGFjYWM0
  tenant_id: YTlhOGUzNzUtZmFjMS00ZWMyLTgyMGEtY2ZiNmViNWNmMDFi
  client_id: YWU5MDFkY2ItNzBkMS00N2ZmLThiMGEtNjZjZGI3ZTU2MjI5
  client_secret: ZjFWOFF+VEdmSFB2NTZaZ3FJRUFzV0xpb2x6RlY2VGFOZmxtSGE5bgo=
