---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/vmfernandezg/tf-controller-helloworld2
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  approvePlan: ''
  #disableDriftDetection: true 
  disableDriftDetection: false 
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  #backendConfig:
    #customConfiguration: |
      #backend "azurerm" {
        #resource_group_name  = "RG-WE-P-TF-01"
        #storage_account_name = "azureaksbackup"
        #container_name       = "tfstate"
        #key                  = "helloworld.tfstate"
      #}
  writeOutputsToSecret:
    name: terraform-outputs
  runnerPodTemplate:
    spec:
      #image: vfernandezg/tf-runner:azure
      #envFrom:
      #- secretRef:
          #name: mysecret # MO ACTUALIZA A VARIABLE SUBSCRIPTION_ID
      env:
      - name: SUBSCRIPTION
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: subscription_id
      volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "mysecretproviderclass"
  #varsFrom:
  #- kind: ConfigMap
    #name: myconfigmap
    #varsKeys:
    #- subscription_id
    #- tenant_id
    #- client_id
    #- client_secret
  varsFrom:
  - kind: Secret
    name: mysecret
